services:
  kv-api:
    container_name: kv-api
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      kv-mysql:
        condition: service_healthy
    volumes:
      - .:/app

  kv-mysql:
    container_name: kv-mysql
    image: mysql:8.0.36-bullseye
    env_file: .env
    user: root
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "${DB_HOST}",
          "-u",
          "${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 5s
      start_period: 20s
      timeout: 5s
      retries: 3
volumes:
  mysql-data:
